apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pod-info
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: flux-overview
  path: "apps/clusters/my-cluster/pod-info"
  prune: true
  timeout: 1m