apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/podinfo
- ../../base/podinfo-helm


patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: not-used
        spec:
          template:
            metadata:
              annotations:
                deployed-with-kustomize: "true" 
      target:
        kind: Deployment
        name: "podinfo"
    - target:
        group: helm.toolkit.fluxcd.io
        version: v2
        kind: HelmRelease
        name: podinfo-helm
      path: helm-patch.yml