apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-overview
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/warroyo/flux-overview
  ref:
    branch: main